site_name: 'Vapor RED - Docs'
copyright: 'Copyright &copy; 2018 Qutheory, LLC'
site_url: 'https://docs.vapor.codes/3.0/'
pages:
- 'Overview': 'index.md'
- 'What are Vapor Red': 'what-are-vapor-red.md'
- 'Getting started': 'getting-started.md'
- 'Providers': [
    'Digital Ocean': 'providers/digitalocean.md'
]
- 'Projects': [
    'Create': 'projects/create.md',
    'Environment': 'projects/environment.md'
]
- 'FAQ': 'faq.md'

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - footnotes
    - meta
    - pymdownx.superfences
    - toc:
        permalink: true
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'purple'
#   logo: 'images/white-cloud-icon.svg'
repo_url: http://github.com/vapor-cloud/docsv2
edit_uri: https://github.com/vapor-cloud/docsv2/edit/master/docs/
extra:
    social:
        - type: 'twitter'
          link: 'https://twitter.com/@codevapor'
        - type: 'slack'
          link: 'http://vapor.team/'
        - type: 'github'
          link: 'https://github.com/vapor'
    font:
        text: 'Roboto Slab'
        code: 'Source Code Pro'
extra_css:
  - 'stylesheets/extra.css'
